[workspace]
channels = ["conda-forge"]
name = "pixi-yolo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
cuda-test = "python -c 'import torch; print(torch.cuda.is_available())'"

[system-requirements]
cuda = "12.8"

[dependencies]
python = ">=3.13.3,<3.14"
cuda-version = "12.8.*"

[pypi-dependencies]
torch = { version = "*", index = "https://download.pytorch.org/whl/cu128" }
torchvision = { version = "*", index = "https://download.pytorch.org/whl/cu128" }
ultralytics = "*"

[pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu128"]
